//
// Created by Gamidoi on 5/3/2026.
//

#ifndef FINALPROJECTCIS164INVENTORYJOBMANAGEMENTDATABASE_JOB_H
#define FINALPROJECTCIS164INVENTORYJOBMANAGEMENTDATABASE_JOB_H


class Job {
};


#endif //FINALPROJECTCIS164INVENTORYJOBMANAGEMENTDATABASE_JOB_H